### ISSUE TITLE
Property "Craft\Import_EntriesRecord.versionId" is not defined.

### ISSUE THREAD

**Issue by krazyjakee** [boboldehampsink/import#49] opened 2015-04-09 13:27 UTC
Craft is failing to import more than 1 entry. Doesn't matter which entries I import, it imports one successfully and then stops dead. Looks like all the data is there it just can't seem to continue on to the next item in the queue.

```
2015/04/09 13:24:13 [info] [application] [Forced] Starting task Import that has a total of 5 steps.
in /home/nexusdev/sites/newport-caravans/craft/app/services/TasksService.php (227)
2015/04/09 13:24:13 [info] [application] [Forced] Starting step 1 of 5 total steps.
in /home/nexusdev/sites/newport-caravans/craft/app/services/TasksService.php (235)
2015/04/09 13:24:13 [error] [application] Encountered an error running task 537 (Import), step 1 of 5: An exception was thrown: Property "Craft\Import_EntriesRecord.versionId" is not defined.
```

**Comment by boboldehampsink** [comment] 2015-04-09 13:27
Duplicate of #45

**Closed by boboldehampsink** 2015-04-09 13:27 UTC
