### ISSUE TITLE
Categories & assets not importing

### ISSUE THREAD

**Issue by theswebsite** [boboldehampsink/import#119] opened 2016-06-10 15:58 UTC
I can't seem to get any categories or assets to import correctly. I used the Export plugin to export data and change a few things then re-import. Everything is successful until I go to the entry in Craft and see that no categories or assets have been mapped to the entry.

Many thanks

**Comment by boboldehampsink** [comment] 2016-06-27 06:27
This seems to be a duplicate of #107

**Closed by boboldehampsink** 2016-06-27 06:27 UTC

**Comment by muerl** [comment] 2017-10-26 15:40
FYI this is a duplicate of #106 not #107
