### ISSUE TITLE
modifyImportRow hook kills search features when importing

### ISSUE THREAD

**Issue by peternorbeck** [boboldehampsink/import#111] opened 2016-04-21 18:18 UTC
Hi,

I'm using the modifyImportRow hook to import to a matrix field with success.  That's good.

The bad thing is when i finally succeeded I saw that the import search smartness for my other fields in the csv of types like entries, categories, assets, multioptions etc failed to import.  I mean the feature where you can import an image by its filename or an entry by it's title.  Is that supposed to still work when you use the modifyImportRow hook? 

I'm testing with the raw hook template. When I do the import features don't work for me. 

```
public function modifyImportRow($element, $map, $data)
{
    // Map data to fields
    $fields = array_combine($map, $data);

    // Initialize content array
    $content = array();

    // Arrange your content in a way that makes sense for your plugin
    foreach ($fields as $handle => $value) {
        $content[$handle] = $value;
    }

    // Set modified content
    $element->setContentFromPost($content);
}

```

Thanks for an asume plugin!

**Comment by boboldehampsink** [comment] 2016-05-11 09:03
This is a duplicate of #106

**Closed by boboldehampsink** 2016-05-11 09:03 UTC
